export const EVENTS_LOADED = 'EVENTS_LOADED'
export const EVENTS_LOADED_FAILED = 'EVENTS_LOADED_FAILED'
export const EVENTS_LOADED_PENDING = 'EVENTS_LOADED_PENDING'

export const EVENTYPES_LOADED = 'EVENTYPES_LOADED'
export const EVENTYPES_FILTER_SET = 'EVENTYPES_FILTER_SET'
