export const EVENTS_LOADED = 'EVENTS_LOADED'
export const EVENTS_LOADED_FAILED = 'EVENTS_LOADED_FAILED'
export const EVENTS_LOADED_PENDING = 'EVENTS_LOADED_PENDING'

export const EVENTTYPES_LOADED = 'EVENTTYPES_LOADED'
export const EVENTTYPES_FILTER_SET = 'EVENTTYPES_FILTER_SET'
export const EVENTINPUT_FILTER_SET = 'EVENTINPUT_FILTER_SET'
